version: '3.9'

services:
  api-server:
    image: api-server
    ports:
      - 5000:5000
    volumes:
      - ./server/db:/usr/src/app/db
      - ./server/models:/usr/src/app/models
      - ./server/controllers:/usr/src/app/controllers
      - ./server/routes:/usr/src/app/routes
      - ./server/index.js:/usr/src/app/index.js
    depends_on:
      - standalone
  standalone:
    image: mongo:6.0.3
    ports: 
      - 27017:27017
    command: mongod --dbpath /data/db --port 27017 --config /resource/mongod.yml
    volumes:
      - ./standalone/config/mongod.yml:/resource/mongod.yml
      - ./standalone/data:/data/db