version: '3.9'

services:
  standalone:
    image: mongo:6.0.3
    ports: 
      - 27017:27017
    command: mongod --dbpath /data/db --port 27017 --config /resource/mongod.yml
    volumes:
      - ./config/mongod.yml:/resource/mongod.yml
      - ./data:/data/db